config/routes.rb
Rails.application.routes.draw do
  resources :welcomes

  root 'welcomes#index'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<style>
  .feature-img {
    width: 100%;
  }
  .checkmkimg {
    width: 7%;
    float: left;
    padding-right: 5px;
  }
  .signup_btn {
    background-color: transparent;
    border-color: white;
    color: #fff;
    position: relative;
    display: inline-block;
    border: 2px solid;
    padding:15px 42px 15px;
    height: 50px;
    width: 200px;
    border-radius: 5px;
    text-decoration: none;
    font-size: 12px;
    letter-spacing: 0.05em;
    font-weight: 700;
    text-transform: uppercase;
    -webkit-transition: all .5s ease-out;
         -o-transition: all .5s ease-out;
            transition: all .5s ease-out;
  }
  .signup_btn:hover {
    border-color: #09c;
    background-color: #09c;
    color: #fff;
    text-decoration: none;
  }
</style>

<head>
  <title>Security | ThinkRTC</title>
</head>
<meta name="viewport" content="width=device-width; initial-scale = 1.0; maximum-scale=1.0; user-scalable=no" />
<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">

<!-- Home -->
<main id="home" class="masthead-video masked">
  <img class="video" src="http://shubucyber.in/wp-content/uploads/2016/03/online-security-Feature_1290x688_MS.jpg" alt="customer support">
  <div class="opener rel-1">
    <div class="container">
      <div class="row">
        <center>
        <div class="lead col-lg-6" style="float:none">
          <h1 class="wow fadeInDown">Encrypted media and signaling</h1>
          <p class="lead-text">Our encrypted and authenticated infrastructure means that your customer data is always private and secure.</p>
        </div>
        <br>
        <div class="lead-controls">
          <div class="row-fields row">
              <a href="/sign_up" class="signup_btn hvr-grow">try it now</a>
          </div>
        </div>
        </center>
      </div>
    </div>
  </div>
</main>

  <!-- Content -->
<div class="content">
  
  <!--Industry section 2-->
  <section id="features1" class="features section" style="background: #09c">
    <div class="container">
      <header class="header" style="padding: 0px; border-bottom: 1px solid #fff;">
        <h1 style="color: #fff">Why It's Important</h1>
      </header>
      <div class="row-columns row-padding row" style="padding-top: 35px">  
        <div class="col-feature-img column column-padding col-md-6 text-center wow fadeInLeft">
            <img class="feature-img" style="box-shadow: none" src="<%=asset_path'trtcsecurity'%>">
        </div>
        <div class="col-feature column column-padding col-md-6">
          <ul class="features">
            <li>
              <img class="checkmkimg" src="https://static.opentok.com/img/platform/body-icon-check_mark@2x.png">
              <h3 style="color: #fff">We recognize that security is an essential consideration.</h3>
            </li>
            <br>
            <li>
              <img class="checkmkimg" src="https://static.opentok.com/img/platform/body-icon-check_mark@2x.png">
              <h3 style="color: #fff">Sensitive user information remains secure.</h3>
            </li>
            <br><br>
            <li>
              <img class="checkmkimg" src="https://static.opentok.com/img/platform/body-icon-check_mark@2x.png">
              <h3 style="color: #fff">We stay up to date with the latest security technologies.</h3>
            </li>
            <br>
            <li>
              <img class="checkmkimg" src="https://static.opentok.com/img/platform/body-icon-check_mark@2x.png">
              <h3 style="color: #fff">Offer fully confidential calls and services to your customers.</h3>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
    
  <!--Industry section 3 box half one-->
  <section class="main end" style="padding-top:100px; background-image: url(https://static.opentok.com/img/platform/dots.png)">
    <div class="container">
      <div class="clearfix">
        <section class="integrations" style="background: transparent">
          <center>
            <img src="<%=asset_path'pii'%>" alt="personal information">
            <h2>We Don’t Collect PII</h2>
          </center>
            <p>With ThinkRTC, all your user data is anonymized. End user data including logins, IP addresses, identities, payment information and more are never shared with anyone.</p>
            <br>
        </section>
        <section class="cta" style="background: transparent">
          <center>
            <img src="<%=asset_path'likesecurity'%>" alt="security">
            <h2>Encryption</h2>
          </center>
            <p>We use industry standard security technologies such as HTTPS support, secure RTP, HTTP authentication, secure WebSockets and application level authentication using tokens. This ensures that your information is always safe, whether it’s media, API or messaging traffic.</p>
        </section>
      </div>
    </div>
  </section>
 
 <!--Industry section 4 box half two-->
  <section class="main end" style="background-image: url(https://static.opentok.com/img/platform/dots.png)">
    <div class="container">
      <div class="clearfix">
        <section class="integrations" style="background: transparent">
          <center>
            <img src="<%=asset_path'encryption'%>" alt="encryption">
            <h2>Encrypted Archiving</h2>
          </center>
            <p>With Encrypted Archiving archived data is never unencrypted at rest or in transit providing the highest level of security. This enables customers to meet the most stringent of compliance and regulatory requirements</p>
        </section>
        <section class="cta" style="background: transparent">
          <center>
            <img src="<%=asset_path'safeharbor'%>" alt="safe harbor">
            <h2>Safe Harbor Compliant</h2>
          </center>
            <p>The ThinkRTC platform is a safe harbor. If you’re building an application with strict security requirements, such as a wealth management service, we’ll work with you to make sure your application is built to comply.</p>
        </section>
      </div>
    </div>
  </section>


</div>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>